### ISSUE TITLE
question about blog

### ISSUE THREAD

**Issue by geoHeil** [Laurae2/Laurae#10]
Hi @Laurae2 , I did not find your e-mail address. Just wanted to say I quite like your blog https://sites.google.com/view/lauraepp/blog would you mind adding a feed that an RSS reader could subscribe to it?

**Comment by Laurae2** [comment]
@geoHeil Use this instead: https://help.medium.com/hc/en-us/articles/214874118-RSS-feeds

As the website (https://sites.google.com/view/lauraepp/blog) is hosted on the New Google Sites, I have no idea what is feasible with it.

I am currently on the process of moving stuff to the old Google Sites, while adding lot of tutorials.

Pages with RSS available:
* https://medium.com/@Laurae2
* https://medium.com/data-design
* https://medium.com/implodinggradients

Tell me if creating RSS feeds from them is possible.

**Comment by geoHeil** [comment]
thanks I will try to follow on medium then.
