### ISSUE TITLE
data.table installation instructions

### ISSUE THREAD

**Issue by eddelbuettel** [Laurae2/Laurae#5]
data.table is now at 1.10.4 which ships with fread and fwrite so I think you can just point to CRAN.

**Comment by Laurae2** [comment]
@eddelbuettel I updated description with your update with 71b8664 so the user does not have to compile data.table by themselves (so they can use directly CRAN like other packages), thanks!

**Comment by eddelbuettel** [comment]
Thanks.  One comment, if I may:  it depends on the OS.  Many of us have one with 'x' in the name where you always compile from source.

The main point of this suggestion was that the *released* version has the feature you (correctly) advertise.  No need to install potentially risky unreleased dev versions.
